name: share
description: Flutter plugin for sharing content via the platform share UI, using
  the ACTION_SEND intent on Android and UIActivityViewController on iOS.
  Receiving ACTION_SEND + ACTION_SEND_MULTIPLE on Android
version: 0.7.0
author: Surbhi Kumari
homepage: https://github.com/sur16-cse/flutter-share-app-to-app.git
#author: Flutter Team <flutter-dev@googlegroups.com>
#homepage: https://github.com/flutter/plugins/tree/master/packages/share

flutter:
  plugin:
    androidPackage: io.flutter.plugins.share
    iosPrefix: FLT
    pluginClass: SharePlugin

dependencies:
  meta: ^1.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.4.2
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=0.1.4 <3.0.0"
